### ISSUE TITLE
サイバーエージェントさま　求人情報掲載

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#104]
プラン：将軍

---

サイバーエージェント アドテクスタジオでは一緒に働ける仲間を募集中です。
アドネットワーク、リワード、RTB、DMPなど多岐にわたるインターネット広告プロダクト開発を行っており、インターネット広告最大級のトラフィックを受ける広告システム開発に携われるのも魅力です。

■アドテクスタジオの魅力
10Gbpsを超える広告トラフィック
数十PBクラスのデータ基盤
Aerospike,Matrix,MAPRなど最新ミドルウェア利用
少数精鋭のチームでスピード感ある開発
アドテクスタジオのエンジニアは現在約300名。横の繋がりでスキルアップしやすい

Scalaの関数型の特徴を活かすことにより、副作用の少ないシステムを作ることが出来るため、アドテクスタジオ内のプロダクトで採用事例が増えています。また、Scalaへの貢献・拡大に力を入れており、Scala
Matsuriの協賛・運営サポートやSparkへのコントリビュート、勉強会の開催などを行ってます。

業務は既存システム改修、新機能開発、新規事業の立上げなど様々です。
事業を進めるにあたりスピードが求められるのはもちろん、高いスキルが求められます。是非ご応募ください。

**Comment by tkawachi** [comment]
求人情報は応募先にリンクしたい感があります。

**Comment by taisukeoe** [comment]
応募先というのはメール？Webサイト？フォーム？
「応募先"に" リンクしたい」ということは、こちらからではなく、あちらからかな？

具体的にどういうことか、スポンサー向け案内文なりなんなりで例示してもらえますかー

**Comment by tkawachi** [comment]
これは作りかけのものですが、青いボタンを置きたいな、と思ったという話です。

![screen shot 2015-08-22 at 16 36 32](https://cloud.githubusercontent.com/assets/22657/9423019/00508f7c-48ec-11e5-93f1-d56736006f09.png)
