### ISSUE TITLE
国平さまロゴ掲載

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#120]
プラン：忍者
リンク先：https://pbs.twimg.com/profile_images/3098931127/b08fec5532955bcdfc1d43ef4f0174a2.png
ロゴ：https://twitter.com/kuchitama

**Comment by Kuchitama** [comment]
リンク先とロゴが逆ですねｗ

リンク先：https://twitter.com/kuchitama
ロゴ：https://pbs.twimg.com/profile_images/3098931127/b08fec5532955bcdfc1d43ef4f0174a2.png

**Comment by taisukeoe** [comment]
おおっと失礼しましたｗ
