### ISSUE TITLE
Tomer Gabel さんの画像が参照切れ

### ISSUE THREAD

**Issue by tkawachi** [scalajp/2016.scalamatsuri.org#164]
![2015-09-12 2 25 48 pm](https://cloud.githubusercontent.com/assets/22657/9830047/d794ff3a-595a-11e5-902d-6844e9eaaffb.png)

**Comment by tkawachi** [comment]
アイコン画像は直接参照ではなく、コピーを作成して repository に追加し、参照したほうが良さそう。

**Comment by okapies** [comment]
先方から頂いてたアドレスが dropbox で切れちゃったんですね。「アイコンがリンク切れになっちゃったので頂戴」ってメールしますか。 ref. scalajp/2015#266

**Comment by okapies** [comment]
Twitter で _"May I trouble you to re-submit your icon?"_ とかって送ろうと思いますがどうしましょ。企画のタスクとして対応してもらった方が良い？

**Comment by tkawachi** [comment]
@okapies おねがいしますー

**Comment by tkawachi** [comment]
@okapies あざしたー
