### ISSUE TITLE
セプテーニオリジナルさま求人情報掲載

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#167]
セプテーニ・オリジナルは、高い成長を続けるソーシャルメディア（Facebook、Twitterなど）のアドテクノロジー領域や、 
コンシューマ向けの新規サービス領域において、新たな「技術」を用いてサービスを展開しております。

プログラミング言語はScalaがメインになり、コンシューマ向けの 
オリジナル新作マンガの配信サービス「GANMA！(ガンマ)」をはじめ、 
新たに開発中のプロダクトにも積極的にScalaを採用しております。

コードレビューやスクラムの適用などは当然とし、ドメイン駆動設計を取り入れる等、
綺麗なコードを素早くを作ることに注力している職場です。
学習意欲の高いエンジニアが集い、社内での技術情報はもちろん社外の勉強会への参加にも前向きで、 
JIRA・Stashなど、エンジニアドリブンの環境で積極的にCIツールを開発の現場に採用し、
チームでサービスを研ぎ澄ませる仕組みが整っています。

また、ほぼ全ての工程が内製であるため、企画から運用まで携わることが可能です。
トレーニングにも力を入れており、Scala経験者でなくても問題ありません。
ご意向によっては、英語を使う環境も選べます。

一緒に働ける仲間を積極的に募集しておりますので、ぜひご応募ください。

■開発環境
Playframework+Scala/TypeScript+AngularJS/Chef/AWS/Swift 等

＜応募する（http://www.septeni-holdings.co.jp/career/）＞

**Comment by tkawachi** [comment]
やります
