### ISSUE TITLE
Scala Conference in Japan 2013のURLを修正する

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#18]
現状、2014のサブドメインの 2013/ にアクセスする辛み…
http://2014.scalamatsuri.org/2013/ja/program/index.html

サブドメイン切っていただくところからでしょうか？ > @takuya71

**Comment by tkawachi** [comment]
終始得する → 取得する？

**Comment by ntakk** [comment]
2014.scalamatsuri.org と同様に 2013.scalamatsuri.org から scalajp.github.io へのCNAME設定しました。
2014 と同じように 2013用の レポジトリ わけてもらって CNAME ファイル用意していただけると
2013.scalamatsuri.org でアクセス可能になると思います。

**Comment by tkawachi** [comment]
https://github.com/scalajp/2013.scalamatsuri.org つくりました。
http://2013.scalamatsuri.org でアクセスできるはず。

http://2014.scalamatsuri.org/2013/ はリダイレクトしておきますか。

**Comment by tkawachi** [comment]
Fixed by 577db9f9d1cf152763f32ff412603fc5a4101ca8

**Comment by taisukeoe** [comment]
:+1: :+1:
