### ISSUE TITLE
ScalaJPのtwitterやfacebookへのリンク

### ISSUE THREAD

**Issue by tkawachi** [scalajp/2016.scalamatsuri.org#183]
> takezoux2 [11:05 PM] 
> ふと気付いたんですが、ScalaMatsuriの HPに、ScalaJPのtwitterやfacebookへのリンクなくないですか？さまざまな情報はこちらから配信しますみたいな感じで載せておいた方が良い気が

**Comment by takezoux2** [comment]
どの辺にのせるのが良さそうですかね？

**Comment by tkawachi** [comment]
トップページ「Scala Matsuri をシェア」の前後あたりがソーシャルメディアつながりで良いと思います

**Comment by takezoux2** [comment]
開催概要のところに

>  随時このページで公開します。 どうぞご期待ください。

とあるので、この辺に

> 最新情報は随時twitterやfacebookでも公開しますので、フォロー/いいねをお願いします。

とか入れてもいい気もします。

**Comment by tkawachi** [comment]
そこでいい気もしますね

**Comment by taisukeoe** [comment]
良いと思います。
デザイン的に難しいかもですが、 ScalaMatsuriハッシュタグのTLもどっかに載せたいですね。

**Comment by takezoux2** [comment]
とりあえず、開催概要のところに追加してみました。
英語のほうの修正をだれかしてもらえると嬉しいです。

ハッシュタグはどこにのせるのが良さげでしょうかね。
