### ISSUE TITLE
Work around outbound links not working with common ad blockers

### ISSUE THREAD

**Issue by ches** [scalajp/2016.scalamatsuri.org#197]
Since 23a3b51ab78058d0, clicking on outbound links fails for me (meaning I can't click the Tickets section link to go to Doorkeeper, which is a pretty big problem :smile:). Following the discussion on that commit it seems to be because I use an ad blocker extension that's interfering with the Google Analytics JS.

Since this could affect many people who might use ad blockers and reaching the registration is rather important, it seems worth trying to work around this possible failure case. I'll try [some suggested workarounds](https://www.domsammut.com/code/workaround-for-when-the-hitcallback-function-does-not-receive-a-response-analytics-js) once I have a chance to get the site built.

**Comment by tkawachi** [comment]
Which ad blocker are you using? I've tried with [AdBlock](https://getadblock.com/) with Chrome, and the ticket link is working.

**Comment by tkawachi** [comment]
Tried Ghostery, still not able to reproduce this problem. Anyway I'll merge #198. It is harmless for users who are not using adblocker.

Please let me know if the problem still occurs after merging.

**Comment by ches** [comment]
Yes this fixed it for uBlock Origin, thanks @tkawachi!
