### ISSUE TITLE
侍プランのノベルティ配布可否が誤っている

### ISSUE THREAD

**Issue by tkawachi** [scalajp/2016.scalamatsuri.org#225]
スポンサーのノベルティ配布ですが、
侍プラン、

http://scalamatsuri.org/ja/sponsors/ こちらだと◯
http://scalamatsuri.org/ja/sponsors/sponsorship.pdf こちらだと “-“ になっている

**Comment by tkawachi** [comment]
なんだか El capitan に update してから preview の表示がぼやけるので、どなたかスクショとって入れ替えていただけませんか。

![screen shot 2015-10-08 at 16 26 19](https://cloud.githubusercontent.com/assets/22657/10360140/6bdf9ab4-6dd9-11e5-948f-eb7f5552a069.png)

**Comment by daiksy** [comment]
![2015-10-08 16 39 28](https://cloud.githubusercontent.com/assets/568030/10360375/36a3dae8-6ddb-11e5-81b3-d57a16713b5b.png)

スクショとってみました。

**Comment by tkawachi** [comment]
ありがとうございます。後で入れ替えておきます。
