### ISSUE TITLE
CFP の情報を landing page にも載せる

### ISSUE THREAD

**Issue by eed3si9n** [scalajp/2016.scalamatsuri.org#24]
http://scalamatsuri.org/ に飛んでも CFP 情報が一番上のリンクしか無いので見つけづらいです。
「Scala Matsuri をシェア」の上に大きい文字で「セッション募集」とかどうでしょう?
内容的には募集の文面をまとめた感じでいいと思います。

> Scala コミュニティの関心を引きそうなトピックをお待ちしています。1 セッションの時間は 40 分と 15 分の二種類を用意しています。400字以内でトークの概要を書いて、ご応募下さい。 セッションは Matsuri 参加者の投票によって決定されます。締め切りは 10月15日00:00 JSTです。

**Comment by grimrose** [comment]
:+1:

**Comment by taisukeoe** [comment]
:+1:

**Comment by tkawachi** [comment]
:+1:

**Comment by okapies** [comment]
:+1:

**Comment by gakuzzzz** [comment]
チャレンジします

**Comment by tkawachi** [comment]
#35 の内容を index_en.html に英語で載せてくれる人募集です

**Comment by eed3si9n** [comment]
@tkawachi #56?

**Comment by tkawachi** [comment]
ありがとうございました
