### ISSUE TITLE
ChatWorkさま求人情報掲載

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#307]
ChatWork株式会社では「チャットワーク」というクラウド型ビジネスチャットツールを主力事業として展開しています。チャットワークで世界の働き方を変える！というミッションのもと、中小企業をはじめ大企業、教育機関、官公庁など約80,000社、世界183カ国に導入され（2015年10月時点）、各組織の生産性向上やコミュニケーション活性化に貢献しています。

チャットワークではPHPで実装された既存システムを保守し続けることに限界を感じ、ゼロベースで再実装することを決断。現場のエンジニア主導でアーキテクチャ選定合宿を行い、Scalaの採用を決定しました。

参考：チャットワークがScalaを採用する理由、これからのチャレンジ。
http://c-note.chatwork.com/post/91805620020/chatwork-meets-scala

Scala化を決めて1年がたち、チャットワークのScala化プロジェクトも大きく佳境を迎えています。既存の大規模システムを止めることなくリプレースし、今後の機能拡張や負荷に耐えうるアーキテクチャへと変えていくことは技術的に大変なチャレンジとなります。関数型Scala、ドメイン駆動設計(DDD)、最新のAWSによるサーバアーキテクチャをフルに活用したシステムとなっており、エンジニアとして刺激的な環境で開発を行えるのではと思います。

もともと社内ツールとして開発がはじまったチャットワーク。自社でももちろんフルに活用しており、自分たち自身のためにも良くしていきたいと日々活発なアイデアが飛び交っています。ただ言われたシステムをつくるのではなく、ユーザーとしての目線を持ち自分で工夫して開発を行えるエンジニアの方を募集しています。

日本発で世界スタンダードとなるWebサービスをつくっていきたいと思っていますので、ご応募をお待ちしております！

**Comment by tkawachi** [comment]
リンク先は特に指定されていない感じでしょうか？

**Comment by taisukeoe** [comment]
特に指定いただいていないですね。

**Comment by tkawachi** [comment]
ではリンク先なしで merge します
