### ISSUE TITLE
スマホでタイムテーブルのタブ切り替えた状態でスクロールすると、勝手にタブが切り替わる

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#331]
https://twitter.com/takezoen/status/667001198935805952

**Comment by eed3si9n** [comment]
慣れない frontend 系のコードを書いてみた僕のバグですね。
https://github.com/scalajp/2016.scalamatsuri.org/blob/5fc381276d86369a4038a60223caed1849d3c65a/js/scalamatsuri2016.js#L66-L68

jQuery だと、スクロール時に resize event が発火するらしいです。
`$(window).width()` を取得して本当に変わったかチェックとかやる必要があるらしい。
