### ISSUE TITLE
クリックしてもセッション詳細が表示されない

### ISSUE THREAD

**Issue by xuwei-k** [scalajp/2016.scalamatsuri.org#359]
twitterでも声が上がってたので、publicな方にとりあえずissueあったほうがいいと思ったので、作っておく。

以下、適当にslackの発言コピペ

> サイトのプログラムからアブスト読もうとクリックしたらエラーになってて iframe が表示されないようになってました。Github pages の `X-Frame-Options` って前から `DENY` でしたっけ?
> 
>  X-Frame-Options を手動で設定した覚えは自分はないです。もしかしたら GitHub pages の設定がかわったのかも

https://twitter.com/megascus/status/687196292380938241
https://twitter.com/pocketberserker/status/687196120766779392

**Comment by eed3si9n** [comment]
対応中です。
