### ISSUE TITLE
Facebook及びTwitterのシェア画像の英語版を用意する

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#4]
英語版ページのog:image及びtwtter:imageでも現在[日本語版の画像](http://scalamatsuri.org/img/common/img_repre2.png)を参照してしまっているのを、英語版画像を作成しそちらに変更する。

![ソーシャルシェアの画像](http://scalamatsuri.org/img/common/img_repre2.png)

**Comment by tkawachi** [comment]
これ納品物中の psd/index_des.psd から作成するのが良いと思うのですが、私 Photoshop 持ってないんです。Photoshop をお持ちの方、画像の作成をお願いできないでしょうか。

**Comment by taisukeoe** [comment]
了解です。やります。
