### ISSUE TITLE
資料のリンクを出来る限り全部載せる

### ISSUE THREAD

**Issue by xuwei-k** [scalajp/2016.scalamatsuri.org#409]
このissue作成時点で載ってない人一覧

ひとまずメインの1日目の発表
- [x] @tototoshi "Playソースコード完全マスターへの道"
- [x] huntchr "リアクティブ・マイクロサービス"
- [x] @j5ik2o "sbt-awsプラグインを使って簡単デプロイ"

一日目ではないけど、事前に資料もらって翻訳してた？という意味ではscala-jsコミッターの発表も？

その他、ランチタイムLTや2日目アンカンファレンスも、あれば載せる。

**Comment by xuwei-k** [comment]
そもそも内部的には大抵スライド提出してもらって運営が持ってるはずなので、発表者がpublicなところに上げてなかったら、こっちでこのリポジトリにpdfなどの資料登録してしまう手はある？けど、一部だけそれやるのも統一感なくて微妙な感じするし、できればpublicなところに上げてもらったほうがよい？
もしくはScalaMatsuriのアカウントでslideshareとかspeakerdeck的なところにアップロード？

いずれにせよ、それができるのは1日目と2日目の一部のものであって、アンカンファレンスはたぶん不可能だけれど

**Comment by taisukeoe** [comment]
2/13（土)までにアップしたもののリンク先を教えて欲しい、そこを過ぎたら提出済みのものをこちらでアップしてリンク貼ります、という感じで全員にping飛ばします

**Comment by taisukeoe** [comment]
３人にping飛ばしました。

**Comment by taisukeoe** [comment]
Christopherさんアップロードokでた

**Comment by taisukeoe** [comment]
tototoshiさん
https://speakerdeck.com/tototoshi/steps-to-master-the-play-source-code

かとじゅんさん
https://docs.google.com/presentation/d/1fA5xNLLFHvtvVU6ptdXMHRHSjC7UlSwAMqWO5qANK_4/pub?start=false&loop=false&delayms=3000&slide=id.g1076c6f987_3_0

ChristopherHuntさん
http://www.slideshare.net/scalaconfjp/reactive-microservices-with-play-and-akka

**Comment by taisukeoe** [comment]
fixed.
