### ISSUE TITLE
英語版へのリンクボタンを設置する

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#5]
現在[英語版ページ](http://scalamatsuri.org/index_en.html)へのリンクボタンがなく、英語版が存在していることにトップページから気づかないので、ボタンなりタブなりを設置する

参考:[ScalaMatsuri 2014のトップページ](http://2014.scalamatsuri.org/)では右上にボタン有り。

**Comment by tkawachi** [comment]
最初は英語ページがない状態だったのでリンクはコメントアウトしています。
コメントインして URL を指定すれば良いはず…

**Comment by taisukeoe** [comment]
:+1:
