### ISSUE TITLE
日英版のツイートボタンのカウント数を合計表示にする

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#6]
現在、[英語版ページ](http://scalamatsuri.org/index_en.html)の最下部のツイートボタンが０からになってしまっているのを、日英合算で表示するようにしたい。

**Comment by tkawachi** [comment]
カウント数はシェアした URL に対して行われるみたいですね。

日英でカウントを合計するには日英でシェアする URL を一つにする必要があります。
方法としては、
1. シェアする URL は英語ページにする。日本語話者はリンクをたどって日本語ページを参照する。
2. シェアする URL はなんらかの方法で読者の環境を判別し、日本語と英語のページを出し分ける。

のどちらかですかね…

**Comment by tkawachi** [comment]
https://dev.twitter.com/web/tweet-button/parameters#button の counturl でいけるかな？

**Comment by tkawachi** [comment]
counturl を英語のページに統一すると日本語のページをつぶやいてもカウントアップされない。逆もしかり。
なので、統一は諦めましょう。
