### ISSUE TITLE
応募一覧と詳細を行き来した際に迷子になりやすい

### ISSUE THREAD

**Issue by tkawachi** [scalajp/2016.scalamatsuri.org#61]
1. 一覧を見る
2. 詳細を見る
3. 一覧に戻る
4. 次の詳細を見る

という動作をするときに 1 と 3 で一覧の順序が入れ替わっているので、迷子になりやすい。

セッションの間か、一定時間の間は順序を入れ替えないようにしたほうが良い？

**Comment by gakuzzzz** [comment]
ページ遷移じゃなくて下ににょきっと生えるようなUIにする、とか？

**Comment by okapies** [comment]
今くらいの文章量なら、その方法でもそんなに busy にならずに済みそうですね。

**Comment by eed3si9n** [comment]
nescala の場合は一覧にアブストラクトも載ってます - http://www.nescala.org/2015/talks

Scala Days の場合は同じページ内にモーダル・ダイアログが出てくる - http://event.scaladays.org/scaladays-amsterdam-2015#!#schedulePopupExtras-6884
