### ISSUE TITLE
CFP応募者のIconがなかった場合のNo Image画像を用意する

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#75]
現状空欄になるため、若干見栄えが崩れてしまう問題。

関連: https://github.com/scalajp/2016.scalamatsuri.org/pull/74

**Comment by gakuzzzz** [comment]
:+1:

**Comment by gakuzzzz** [comment]
https://www.iconfinder.com/search/?q=no+image&license=2  商用フリー、リンク不要

http://findicons.com/search/no-image#ajax 商用フリー、リンク不要で絞込み可

**Comment by gakuzzzz** [comment]
とりあえず真っ白なno_img.pngを登録しておきました。

ファイルの差し替えはお好みで :)
