### ISSUE TITLE
ChatWorkさまロゴ掲載

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2016.scalamatsuri.org#98]
プラン：将軍
ロゴ: http://www.chatwork.com/ja/download/cw_logo.html
ロゴリンク先：http://www.chatwork.com/ja/

> こちらのページに、ガイドライン、各種ロゴデータがあります。
> トップページ用ですと黒背景の横並びロゴが良いでしょうか。

とのことです。

**Comment by tkawachi** [comment]
やります
